### ISSUE TITLE
VLikelihoodFitter:User accessible profile likelihood scans

### ISSUE THREAD

**Issue by steob92** [VERITAS-Observatory/EventDisplay_v4#117]
https://github.com/VERITAS-Observatory/EventDisplay_v4/pull/113#discussion_r629967271

Save a user accessible profile likelihood scan for flux points and spectral fit values. This can serve as a fallback for failed fits or parameter estimation.

**Comment by GernotMaier** [comment]
I am closing this, as we do not expect to make progress on this topic
