### ISSUE TITLE
makeRadialAcceptance unknown argument and use of loadSimpleFileList for a long run list

### ISSUE THREAD

**Issue by jywoo0116** [VERITAS-Observatory/EventDisplay_v4#243]
Making run-wise radial acceptance plots for RBM as part of ANALYSIS.anasum_parallel_from_runlist.sh fails due to the following errors.

1. The argument option -i does not exist for makeRadialAcceptance. (ANALYSIS.anasum_sub.sh line 172 should be removed.)
2. The input run list for makeRadialAcceptance (FLIST in ANALYSIS.anasum_sub.sh) is a long list, not a short list. makeRadialAcceptance.cpp line 84 should use loadLongFileList, not loadSimpleFileList.

Error 2 was found after removing line 172 in ANALYSIS.anasum_sub.sh and rerunning  ANALYSIS.anasum_parallel_from_runlist.sh. Attached are the log files #####.anasum.radialAcceptance.log for error 1 and error 2, respectively.

[66658.anasum.radialAcceptance.log_1.log](https://github.com/VERITAS-Observatory/EventDisplay_v4/files/11953705/66658.anasum.radialAcceptance.log_1.log)

[66658.anasum.radialAcceptance.log_2.log](https://github.com/VERITAS-Observatory/EventDisplay_v4/files/11953706/66658.anasum.radialAcceptance.log_2.log)

**Comment by GernotMaier** [comment]
I actually have removed the functionality to make run-wise radial acceptances in the current development version. I think this has not been tested enough and it only works for long runs and cuts with reasonable high background rates, otherwise statistics are too low. I don't think we should use it.

**Comment by jywoo0116** [comment]
Thank you for the quick response, Gernot! Then are we supposed to generate our own acceptance plot? Could you give me some tips for selecting proper runs (and how many of them) to generate the acceptance plot? Or are there wiki pages that I could look at?

**Comment by GernotMaier** [comment]
Yes, best is to generate your own acceptance curves. You should select for this runs with similar observational parameters in zenith, azimuth, and NSB range. 

For very very weak sources, it is acceptable to use the same field of view as for the analysis for the generation of radial acceptances (which makes finding runs with similar patterns easier).

**Comment by GernotMaier** [comment]
This issue has been solved.
