### ISSUE TITLE
make VTS.analyzeMuonRings fails for v490.2

### ISSUE THREAD

**Issue by qi-feng** [VERITAS-Observatory/EventDisplay_v4#245]
make VTS.analyzeMuonRings fails for v490.2; it worked on the same system for v487c. 
The output is pasted below. Thank you in advance. 

> qifeng@analysis:/usr/local/veritas/nextday/EventDisplay_v4$ make VTS.analyzeMuonRings
> g++ -O obj/VGlobalRunParameter.o obj/VGlobalRunParameter_Dict.o obj/VImageCleaningRunParameter.o obj/VImageCleaningRunParameter_Dict.o obj/VEvndispRunParameter.o obj/VEvndispRunParameter_Dict.o obj/VDB_Connection.o obj/Ctelconfig.o obj/Cshowerpars.o obj/Ctpars.o obj/VTS.analyzeMuonRings.o -L/usr/local/veritas/packages/root-6.24.06/root_624_install/lib -lGui -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -lm -ldl -rdynamic -lMLP -lTMVA -lMinuit -lXMLIO -lSpectrum -lgsl -lgslcblas -lm -L/usr//lib64 -lcfitsio -lcfitsio -o ./bin/VTS.analyzeMuonRings
> obj/VEvndispRunParameter.o: In function `VEvndispRunParameter::updateInstrumentEpochFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
> /usr/local/veritas/nextday/EventDisplay_v4/src/VEvndispRunParameter.cpp:1021: undefined reference to `VSkyCoordinatesUtilities::getMJD_from_SQLstring(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double&, double&)'
> /usr/local/veritas/nextday/EventDisplay_v4/src/VEvndispRunParameter.cpp:1011: undefined reference to `VSkyCoordinatesUtilities::getMJD_from_SQLstring(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double&, double&)'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:1255: VTS.analyzeMuonRings] Error 1

> qifeng@analysis:/usr/local/veritas/nextday/EventDisplay_v4$ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
> OFFLOAD_TARGET_NAMES=nvptx-none
> OFFLOAD_TARGET_DEFAULT=1
> Target: x86_64-redhat-linux
> Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
> Thread model: posix
> gcc version 8.5.0 20210514 (Red Hat 8.5.0-19) (GCC) 
> You have new mail in /var/spool/mail/qifeng

> qifeng@analysis:/usr/local/veritas/nextday/EventDisplay_v4$ echo $ROOTSYS 
> /usr/local/veritas/packages/root-6.24.06/root_624_install

**Comment by GernotMaier** [comment]
Thanks for reporting it - was actually quite easy to fix with adding two (missing) lines into the Makefile.

Added also VTS.analyzeMuonRings to the all/VTS target to make sure that such things are found during the testing phase before releases.

Please try the branch [v490.3-dev](https://github.com/VERITAS-Observatory/EventDisplay_v4/tree/v490.3-dev2) and let me know if this fixed the issue.
